version: '3.8'
  
services:

  postgres:
      
    image: postgres:17-bookworm
      
    environment:  # Задаются переменные окружения для инициализации базы данных
      POSTGRES_PASSWORD: "2906" # Указываем пароль от базы данных
      POSTGRES_DB: postgres # Имя базы данных
      
    ports: # Указываем порт
      - "5432:5432" # Пробрасываем порт из контейнера на локальную машину

    volumes: # Указываем docker volume
      - ./out/pgdata:/var/lib/postgresql/data # Пробрасываем файлы в проект из локальной базы данных

    # Проверка "жива ли база". Docker будет ждать, пока БД не станет готова, перед запуском зависимых сервисов
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]  # Команда: утилита pg_isready проверяет готовность PostgreSQL
      interval: 10s  # Проверяет каждые 10 секунд
      timeout: 5s  # Ждать не более 5 секунд
      retries: 5 # После 5 неудачных попыток пометить контейнер как "unhealthy" 
    networks:           # ← ✅ ДОБАВЬ ЭТО
      - app-network  

  service:
    build: . # Собираем проект в текущей директории

    ports:  # Указываем порт
      - "8080:8080" # Пробрасываем порт из контейнера на локальную машину
    
    environment:  # Задаем подключение к database 
      CONN_BD_DOCKER: ${CONN_BD_DOCKER}
      # Строка подключения к базе данных
      # здесь @postgres:5432 — не localhost, а имя сервиса в Docker-сети!
    
    depends_on: # Ждать, пока postgres станет healthy
      postgres: # Имя базы данных
        condition: service_healthy # Гарантия: сервис не стартует, пока БД не пройдёт healthcheck

    networks: # Подключить к сети app-network
      - app-network 


networks: #Имя пользовательской сети
# Контейнеры в одной сети видят друг друга по имени сервиса

  app-network: 
    driver: bridge # Тип сети: мост (стандартный)
    # Контейнеры получают внутренние IP, могут общаться между собой, но изолированы от хоста (кроме проброшенных портов)


    